# Generated by Django 4.0.6 on 2022-08-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='production_cost',
            field=models.FloatField(default=0),
        ),
    ]
